### ISSUE TITLE
about target_sources(tgt PUBLIC ...)

### ISSUE THREAD

**Issue by Sarcasm** [Mizux/plop#1]
Hello,

You got me interested about the use for `target_sources(tgt PUBLIC ...)`:
- https://github.com/google/cctz/pull/83/files/6cd878965d04595624f512546f59682b165ccd00#r224360174

I have some hard time seeing how it can be useful to specify public headers with it, and I started to do some research on what it can be good for.

I found some discussion about it here:
- https://www.reddit.com/r/cpp/comments/65iyxv/embracing_modern_cmake

3 posts that got my attention:
1. https://www.reddit.com/r/cpp/comments/65iyxv/embracing_modern_cmake/dgaq9xu/
2. https://www.reddit.com/r/cpp/comments/65iyxv/embracing_modern_cmake/dgbsutp/
3. https://www.reddit.com/r/cpp/comments/65iyxv/embracing_modern_cmake/dgnbvjo/

And some other information here, on slide 76 (77 on video):
- https://steveire.wordpress.com/2017/11/05/embracing-modern-cmake/

So I guess, my take on this is that it is mostly for niche situations, and it's not useful for declaring public headers.

**Comment by Mizux** [comment]
Agree `target_sources(tgt PUBLIC ...)` seems not intended to expose/list your public headers (kind of equivalent to [bazel hrds](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.hdrs) list)

**Comment by Sarcasm** [comment]
Indeed, for that it's possible that I will start using PUBLIC_HEADERS when the project is structured as a merged layout for sources + private and public headers + unit tests.

For `target_sources(tgt PUBLIC ...)`, maybe people will surprise me in the future with smart use cases.

**Comment by Mizux** [comment]
Seems the CMake 3.23 FILE_SET is the new way...
ref: https://discourse.cmake.org/t/installing-headers-the-modern-way-regurgitated-and-revisited/3238/2

**Comment by Sarcasm** [comment]
Thanks for the follow up!
